name: Set PR Labels

on:
  pull_request_target:
    types: opened

jobs:
  SetLabels:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set Labels
        uses: woocommerce/grow/branch-label@e981c25267d29c39ff6ab1ae4ea09b267efae86c # actions-v3.0.6
