name: Set PR Labels

on:
  pull_request_target:
    types: opened

jobs:
  SetLabels:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set Labels
        uses: woocommerce/grow/branch-label@a81d3fca0166a02a4c25953d250d80d3612db4b8 # actions-v3
