name: Build

on:
  workflow_call:
  push:
    branches:
      - trunk

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  BuildExtensionBundle:
    name: Build extension bundle
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      FORCE_COLOR: 2
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Prepare PHP
        uses: woocommerce/grow/prepare-php@a81d3fca0166a02a4c25953d250d80d3612db4b8 # actions-v3
        with:
          install-deps: "no"

      - name: Prepare node
        uses: woocommerce/grow/prepare-node@a81d3fca0166a02a4c25953d250d80d3612db4b8 # actions-v3
        with:
          node-version-file: ".nvmrc"
          ignore-scripts: "no"

      - name: Build production bundle
        run: |
          echo "::group::Build log"
          npm run build
          echo "::endgroup::"

      - name: Publish dev build to GitHub
        if: ${{ github.event_name == 'push' && github.ref_name == 'trunk' }}
        uses: woocommerce/grow/publish-extension-dev-build@a81d3fca0166a02a4c25953d250d80d3612db4b8 # actions-v3
        with:
          extension-asset-path: woocommerce-google-analytics-integration.zip

      - name: Publish build artifact
        if: ${{ ! ( github.event_name == 'push' && github.ref_name == 'trunk' ) }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: woocommerce-google-analytics-integration.zip
          path: ${{ github.workspace }}/woocommerce-google-analytics-integration.zip
          # Do not bloat the storage. Keep in only long enough for a caller workflow to pick it up and follow up with some manual debugging.
          retention-days: 2
