name: Deploy Product

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy (e.g., 2.1.21)'
        required: true
        type: string
      deploy_wporg:
        description: 'Deploy to WordPress.org'
        required: false
        default: true
        type: boolean
      deploy_woo:
        description: 'Deploy to Woo.com'
        required: false
        default: true
        type: boolean
      deploy_github:
        description: 'Deploy to GitHub'
        required: false
        default: true
        type: boolean
      simulate:
        description: 'Dry run mode'
        required: false
        default: true
        type: boolean
  workflow_call:
    inputs:
      version:
        description: 'Version to deploy (e.g., 2.1.21)'
        required: true
        type: string
      deploy_wporg:
        description: 'Deploy to WordPress.org'
        required: false
        default: true
        type: boolean
      deploy_woo:
        description: 'Deploy to Woo.com'
        required: false
        default: true
        type: boolean
      deploy_github:
        description: 'Deploy to GitHub'
        required: false
        default: true
        type: boolean
      simulate:
        description: 'Dry run mode'
        required: false
        default: true
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      # Checkout the private action repository
      - name: Checkout woo-product-deploy action
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          repository: woocommerce/woo-product-deploy
          ref: trunk
          path: ./.github/actions/woo-product-deploy
          token: ${{ secrets.ORG_DEPLOY_SECRET }}  # Need PAT with access to the action repository

      # Use the action we checked out
      - name: Deploy Product
        uses: ./.github/actions/woo-product-deploy
        with:
          repo_url: https://github.com/woocommerce/woocommerce-google-analytics-integration
          branch: ${{ github.ref_name }}
          version: ${{ inputs.version }}
          node_version: '24'
          npm_version: '11'
          simulate: ${{ inputs.simulate }}
          wporg_release: ${{ inputs.deploy_wporg }}
          wccom_release: ${{ inputs.deploy_woo }}
          github_release: ${{ inputs.deploy_github }}
          deploy_pat: ${{ secrets.ORG_DEPLOY_SECRET }}
          wporg_username: ${{ secrets.WPORG_SVN_USERNAME }}
          wporg_password: ${{ secrets.WPORG_SVN_PASSWORD }}
          partner_user: ${{ secrets.ORG_PARTNER_USER }}
          partner_secret: ${{ secrets.ORG_PARTNER_DEPLOY_SECRET }}
          wccom_product_id: 1442927
