name: E2E Tests

on:
  push:
    branches:
      - trunk
      - "release/**"
  pull_request:
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "wordpress_org_assets/**"
      - ".github/ISSUE_TEMPLATE/**"
      - "changelog.txt"
      - "readme.txt"
      - "languages/**"
  workflow_dispatch:
    inputs:
      wp-rc-version:
        description: 'WordPress version for Release Candidate (ex. 6.3-RC3)'
      wc-rc-version:
        description: 'WooCommerce version for Release Candidate (ex. 8.0.0-rc.1)'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  E2ETests:
    name: E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      FORCE_COLOR: 2
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Prepare PHP
        uses: woocommerce/grow/prepare-php@3a4249a1fc7e39a987d213e578cbcf32abd55980 # actions-v3
        with:
          install-deps: "no"

      - name: Prepare node
        uses: woocommerce/grow/prepare-node@3a4249a1fc7e39a987d213e578cbcf32abd55980 # actions-v3
        with:
          node-version-file: ".nvmrc"
          ignore-scripts: "no"

      - name: Build production bundle
        run: |
          echo "::group::Build log"
          npm run build
          echo "::endgroup::"

      - name: Start wp-env container
        run: npm run wp-env:up

      - name: Install WP release candidate (optional)
        if: github.event.inputs.wp-rc-version != ''
        env:
          INPUT_WP_RC_VERSION: ${{ github.event.inputs.wp-rc-version }}
        run: |
          npm run -- wp-env run cli --config=.wp-env.test.json -- wp core update --version="${INPUT_WP_RC_VERSION}"
          npm run -- wp-env run cli --config=.wp-env.test.json -- wp core update-db

      - name: Install WC release candidate (optional)
        if: github.event.inputs.wc-rc-version != ''
        env:
          INPUT_WC_RC_VERSION: ${{ github.event.inputs.wc-rc-version }}
        run: |
          npm run -- wp-env run cli --config=.wp-env.test.json -- wp plugin update woocommerce --version="${INPUT_WC_RC_VERSION}"
          npm run -- wp-env run cli --config=.wp-env.test.json -- wp wc update

      - name: Download and install Chromium browser.
        run: npx playwright install chromium

      - name: Run tests
        run: npm run test:e2e

      - name: Archive e2e failure screenshots
        if: ${{ always() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
            name: e2e-screenshots
            path: tests/e2e/test-results/report/**/*.png
            if-no-files-found: ignore
            retention-days: 5
