name: JavaScript Linting

on:
  push:
    branches:
      - trunk
    paths:
      - "**.js"
      - .github/workflows/js-linting.yml
  pull_request:
    paths:
      - "**.js"
      - .github/workflows/js-linting.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 2

jobs:
  JSLintingCheck:
    name: Lint JavaScript
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Prepare node
        uses: woocommerce/grow/prepare-node@a81d3fca0166a02a4c25953d250d80d3612db4b8 # actions-v3
        with:
          node-version-file: ".nvmrc"

      - name: Prepare annotation formatter
        uses: woocommerce/grow/eslint-annotation@3a4249a1fc7e39a987d213e578cbcf32abd55980 # actions-v3

      - name: Lint JavaScript and annotate linting errors
        run: npm run lint:js -- --quiet --format ./eslintFormatter.cjs
