name: PHP Coding Standards

on:
  push:
    branches:
      - trunk
    paths:
      - "**.php"
      - composer.json
      - composer.lock
      - .github/workflows/php-coding-standards.yml
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-paths:
    name: Check changed files
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      should-run: ${{ steps.changes.outputs.php }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Check for relevant changes
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: changes
        with:
          filters: |
            php:
              - '**.php'
              - 'composer.json'
              - 'composer.lock'
              - '.github/workflows/php-coding-standards.yml'

  phpcs:
    name: PHP coding standards
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: check-paths
    if: needs.check-paths.outputs.should-run == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Prepare PHP
        uses: woocommerce/grow/prepare-php@3a4249a1fc7e39a987d213e578cbcf32abd55980 # actions-v3
        with:
          php-version: 7.4
          tools: cs2pr

      - name: Log PHPCS debug information
        run: vendor/bin/phpcs -i

      - name: Run PHPCS on all files
        run: vendor/bin/phpcs ./* -q --report=checkstyle | cs2pr
